version: '3'

services:
  app:
    image: registry.papierpain.fr/patricklepigeon/kao:${VERSION}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=cloud-public
        - traefik.constraint-label=cloud-public
        
        ## HTTP ##
        - traefik.http.routers.kao.entrypoints=web
        - traefik.http.routers.kao.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.kao.middlewares=kao-redirect
        # HTTP: middlewares
        - traefik.http.middlewares.kao-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.kao-redirect.redirectscheme.permanent=true
        
        ## HTTPS ##
        - traefik.http.routers.kao-https.entrypoints=websecure
        - traefik.http.routers.kao-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.kao-https.tls=true
        - traefik.http.routers.kao-https.tls.certresolver=letsencrypt
        - traefik.http.routers.kao-https.tls.options=default
        
        ## LOADBALANCER ##
        - traefik.http.services.kao-https.loadbalancer.server.port=80
    networks:
      - cloud-public

networks:
  cloud-public:
    external: true
